### ISSUE TITLE
Tạo file Index để thêm trang chủ

### ISSUE THREAD

**Issue by trthsa** [trthsa/blog-example#1]
Chúng ta cần có 1 file index.html để tạo trang chủ

**Comment by nghianeban02** [comment]
Tôi sẽ tạo 1 file index.html với tất cả các dữ liệu cần có để tạo 1 trang chủ 

Vậy chúng ta sẽ chọn tên trang chủ là gì?

**Comment by trthsa** [comment]
> Tôi sẽ tạo 1 file index.html với tất cả các dữ liệu cần có để tạo 1 trang chủ
> 
> Vậy chúng ta sẽ chọn tên trang chủ là gì?

Chúng ta sẽ chọn tên là Blog One

**Comment by trthsa** [comment]
Đã giải quyết, đóng task!
