### ISSUE TITLE
Thêm tiêu đề cho Website

### ISSUE THREAD

**Issue by trthsa** [trthsa/blog-example#3]
Có tiêu đề lớn về nội dung của Blog

**Comment by hung27422** [comment]
Chúng ta cần để tiêu đề như thế nào

**Comment by trthsa** [comment]
Bạn nghĩ tiêu đề là:

**"Blog về hệ sinh thái & môi trường"** có được không?

**Comment by hung27422** [comment]
> Bạn nghĩ tiêu đề là:
> 
> **"Blog về hệ sinh thái & môi trường"** có được không?

Mình thấy cũng hợp lý

**Comment by nghianeban02** [comment]
> Bạn nghĩ tiêu đề là:
> 
> **"Blog về hệ sinh thái & môi trường"** có được không?

Tôi cũng thấy hợp lí đó

**Comment by trthsa** [comment]
Vậy chúng ta chốt là **"Blog về hệ sinh thái & môi trường"** nhé @hung27422

**Comment by trthsa** [comment]
Task hoàn thành!
