### ISSUE TITLE
Chúng ta cần đổi tên website

### ISSUE THREAD

**Issue by nghianeban02** [trthsa/blog-example#4]

**Comment by nghianeban02** [comment]
Tôi thấy tiêu đề cũ không được hợp lí cho lắm

**Comment by trthsa** [comment]
Vậy mình chọn tên là **"Blog ENV"**, thể hiện sự yêu thiên nhiên nhé!

**Comment by hung27422** [comment]
> Vậy mình chọn tên là **"Blog ENV"**, thể hiện sự yêu thiên nhiên nhé!

Tôi thấy tên này khá oke

**Comment by nghianeban02** [comment]
> Vậy mình chọn tên là **"Blog ENV"**, thể hiện sự yêu thiên nhiên nhé!
Ok, tôi thấy cũng hợp lí

**Comment by trthsa** [comment]
Vậy chúng ta chốt tên **"Blog ENV"**

**Comment by hung27422** [comment]
> Vậy chúng ta chốt tên **"Blog ENV"**

OK

**Comment by trthsa** [comment]
Task hoàn thành!
