### ISSUE TITLE
Chúng ta cần hình nền cho Web

### ISSUE THREAD

**Issue by trthsa** [trthsa/blog-example#7]
Chúng ta cần một hình nền để thu hút nhiều người xem

**Comment by nghianeban02** [comment]
![image](https://user-images.githubusercontent.com/85358691/234766707-a399633b-e7a1-4da2-9d12-c568faa02c49.png)
Ví dụ như hình này đi @trthsa

**Comment by trthsa** [comment]
> ![image](https://user-images.githubusercontent.com/85358691/234766707-a399633b-e7a1-4da2-9d12-c568faa02c49.png) Ví dụ như hình này đi @trthsa

Vậy chúng ta sẽ lấy hình này nhé @qqphong2001
